allowBuilds:
  '@mongodb-js/zstd': set this to true or false
  node-liblzma: set this to true or false
  sharp: true
minimumReleaseAgeExclude:
  - eve@0.20.0
  - "@ai-sdk/*"
  - "@rolldown/*"
  - "@vercel/*"
  - "@workflow/*"
  - ai
  - experimental-ai-sdk-code-mode
  - eve
  - nitro
  - rolldown
  - workflow
